### PR TITLE
Add support for HTTP proxies

### PR DESCRIPTION
**Pull request by foca**
Support using an HTTP proxy by passing a `proxy` hash with the host, port, user, and password to authenticate against the proxy.

### CODE REVIEW

**Comment by cyx** [comment]
Nice it looks simpler than what I anticipated :)

**Comment by pote** [comment]
Come on @cyx, press that magic green "merge" button. 😂

**Comment by cyx** [comment]
Sorry guys!

**Comment by cyx** [comment]
@foca @pote apologize for years of delay. I'll throw my daughter as the excuse card :)

**Comment by pote** [comment]
Don't worry about it, I didn't complain because I needed it, just because I randomly stumbled unto this PR and found it hilarious. 😄

**Comment by cyx** [comment]
Yes, it's hilarious indeed :)

**Comment by foca** [comment]
Oh, I just thought you hated me :'(

**Comment by cyx** [comment]
;)

**Pull request merged**
